import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NYS DCSS | Information for Employers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="alternate" type="application/rss+xml" title="OTDA Press Releases" href="https://otda.ny.gov/news/feed/rss.xml" />
      </Head>


      <div id="header" className="nys-global-header horizontal stacked">
        <div className="nav-toggle">
          <a href="#" role="button" id="nys-menu-control">Navigation menu</a>
        </div>
        {/* <!-- End nav-toggle div --> */}

        <h1><a href="/DCSE/HomePage"><span>Child</span> <span>Support</span></a></h1>

        <ul id="nys-global-nav">
          <li><a href="#" title="Information for Custodial Parents">Custodial Parents</a>

            <ul>
              <li><a href="/dcse/custodial_parent_services.html">Custodial Parent Services</a></li>
              <li><a href="/dcse/custodial_parent_info.html">Custodial Parent Information</a></li>
              <li><a href="/dcse/how_to_apply.html">How To Apply</a></li>
              <li><a href="/dcse/dd_exp.html">Direct Deposit</a></li>
              <li><a href="/dcse/debitcard.html">Debit Card</a></li>
              <li><a href="/dcse/desk_review.html">Desk Review</a></li>
              <li><a href="/DCSE/secure/ViewPayments" id="viewPaymentsDisbursements" data-role-required="cp">View
                Payments &amp; Disbursements</a></li>
              <li><a href="/DCSE/secure/MonthlyNotice_input" id="monthlyNotice" data-role-required="cp">Monthly
                Notice of Payments &amp; Disbursements</a></li>
            </ul>
          </li>
          <li><a href="#" title="Information for Noncustodial Parents">Noncustodial Parents</a>

            <ul>
              <li><a href="/dcse/non_custodial_parent_services.html">Noncustodial Parent Services</a></li>
              <li><a href="/dcse/enf_actions.html">Enforcement Actions</a></li>
              <li><a href="/dcse/enfUtil.html">Enforcement Actions Assistant</a></li>
              <li><a href="/DCSE/secure/ViewPayments" id="viewPayments" data-role-required="ncp">View Payments</a>
              </li>
              <li><a href="/DCSE/secure/CreatePaymentCoupon" id="paymentCoupon" data-role-required="ncp">Create
                Payment Coupon</a></li>
            </ul>
          </li>
          <li><a href="#" title="Information for Employers" className="capitalize">Employers</a>
            <ul>
              <li><a href="/dcse/employers_new.html" className="capitalize">Employers</a></li>
              <li><a href="https://nynewhire.com/index.jsp" title="Go to New Hire site; new window"
                id="employersNewHire" target="_blank" rel="noopener noreferrer">Report New Hires</a></li>
              <li><a href="/dcse/whbr_new.html">Provide Information
                (<abbr title="Wage and Health Benefits Report">WHBR</abbr>)</a></li>
              <li><a href="/dcse/iwo_calc.html">Calculator</a></li>
              <li><a href="/dcse/iex_notice.html">Income Withholding for Support</a></li>
              <li><a href="/dcse/iex_worksheet.html">Withholding Limitations</a></li>
              <li><a href="/dcse/iex_cases.html">Cases with Prorated Amounts</a></li>
              <li><a href="/dcse/medx_new.html">Dependent Health Insurance</a></li>
              <li><a href="/dcse/remit.html">Remit Payments</a></li>
              <li><a href="/dcse/terminations.html">Report Terminations</a></li>
              <li><a href="/dcse/employers_FAQ.html"><span className="capitalize">Employers</span> <abbr
                title="Frequently Asked Questions">FAQ</abbr></a></li>
            </ul>
          </li>

          <li><a href="#" title="Information for Providers">Providers</a>
            <ul>
              <li><a href="/dcse/providers.html">Providers</a></li>
              <li><a href="/dcse/aop_howto.html"><abbr title="Acknowledgment of Parentage">AOP</abbr>
                Instructions</a></li>
              <li><a href="/dcse/aop_faq.html"><abbr title="Frequently Asked Questions">FAQ</abbr>
                for Acknowledgment of Parentage</a></li>
              <li><a href="/dcse/aop_forms.html">Download Forms</a></li>
              <li><a href="/dcse/access_visitation.html">Supervised Visitation</a></li>
            </ul>
          </li>
          <li><a href="/DCSE/LocalOffices_input" title="Locations of Local County Child Support Offices">Local Offices</a></li>
          <li><a href="#" title="Resources" id="resources">Resources</a>
            <ul>
              <li><a href="/dcse/resources.html">Resources</a></li>
              <li><a href="/dcse/publications.html">Publications &amp; Forms</a></li>
              <li><a href="/dcse/parentage_establishment.html">Establishment of Parentage</a></li>
              <li><a href="/dcse/support_enforcement.html">Support Enforcement</a></li>
              <li><a href="/dcse/nonIVDcases.html">Non-IV-D Services</a></li>
              <li><a href="/dcse/help.html">Help</a></li>
            </ul>
          </li>
          <li><a href="/dcse/site_map.html">Site Map</a></li>
          <li id="select"></li>
          <li id="my-accounts"></li>
          <li id="log-in-out" className="log-in-out"></li>
          <li>
            <form id="siteSearch" method="get" action="https://search.its.ny.gov/search/">

              <h2 className="hide"><label htmlFor="q"><a
                href="https://search.its.ny.gov/search?entqr=0&amp;ud=1&amp;sort=date%3AD%3AL%3Ad1&amp;output=xml_no_dtd&amp;oe=UTF-8&amp;ie=UTF-8&amp;client=otda_frontend&amp;proxystylesheet=otda_frontend&amp;site=otda_collection">Search
                OTDA</a> <span className="icon-search"> </span></label></h2>


              {/* <input tabIndex="0" type="hidden" name="entqr" value="0" />
					<input tabIndex="0" type="hidden" name="ud" value="1" />
					<input tabIndex="0" type="hidden" name="sort" value="date:D:L:d1" />
					<input tabIndex="0" type="hidden" name="output" value="xml_no_dtd" />
					<input tabIndex="0" type="hidden" name="oe" value="UTF-8" />
					<input tabIndex="0" type="hidden" name="ie" value="UTF-8" />
					<input tabIndex="0" type="hidden" name="client" value="otda_frontend" />
					<input tabIndex="0" type="hidden" name="proxystylesheet" value="otda_frontend" />
					<input tabIndex="0" type="hidden" name="site" value="otda_collection" />
					<input type="search" id="q" name="q" maxLength="200" placeholder="Search OTDA" value="" />
					<button type="submit" style="background:#fff;border:none;"><span className="icon-search"><span
								className="hide">Go</span></span></button> */}

            </form>
          </li>
        </ul>

      </div>
      {/* <!-- End header div --> */}


      <div id="content" className="content-page content">

        {/* <!-- InstanceBeginEditable name="pageHead" --> */}
        <h1>Information for Employers</h1>
        {/* <!-- InstanceEndEditable --> */}
        <noscript>
          <div id="jsoff" className="warn">
            <h2>Enable JavaScript to access your account</h2>
            <p>To access your account information, please enable JavaScript in your browser.
              <a href="/dcse/enable_js.html">
                Follow these instructions to enable JavaScript.</a></p>

            <p>You can receive your payment information by phone at
              <strong><abbr translate="no" dir="ltr" className="nowrap"
                title="Teletypewriter: 866-875-9975; Video Relay Service: https://fcc.gov/encyclopedia/trs-providers">1-888-208-4485</abbr></strong>
              (<abbr title="Teletypewriter" translate="no">TTY</abbr>: <strong translate="no" dir="ltr" className="nowrap">1-866-875-9975</strong>),
              Monday&ndash;Friday, 8:00 AM&ndash;7:00 PM.</p>
          </div>
        </noscript>

        {/* <!-- InstanceBeginEditable name="content" --> */}

       
   
    
        <h2 id="emplPubsIP">Employer Publications</h2>
        {/* <!-- FIXME This should be a class --> */}
        <ul className='empresources'>
          <li>
            <a href="/dcse/pdfs/CSRefGuideEmployers.pdf">Reference Guide for Employers</a>
            (<abbr title="Portable Document Format" translate="no">PDF</abbr>)
          </li>
          {/* <!-- FIXME This should be a sublist with a class --> */}
          <li className="m-s-15px">
            <a href="/dcse/pdfs/CSRefGuideEmployers-SP.pdf">
              <bdo dir="ltr" lang="es" translate="no">ESPAÑOL: Gu&iacute;a de Referencia
                para Empleadores sobre Sustento de Menores</bdo>
            </a>
            (<abbr title="Portable Document Format" translate="no">PDF</abbr>)
          </li>
          <li>
            <a href="/dcse/pdfs/CSFS_QuickRef.pdf">
              Quick Reference Guide for Employers and Income Withholders
            </a> (<abbr title="Portable Document Format" translate="no">PDF</abbr>)
          </li>
          <li>
            <a href="/dcse/pdfs/CSFS_NewHire.pdf">New Hire Reporting</a>
            (<abbr title="Portable Document Format" translate="no">PDF</abbr>)
          </li>
          <li>
            <a href="/dcse/pdfs/CSFS_IndContractors.pdf">Independent Contractors</a>
            (<abbr title="Portable Document Format" translate="no">PDF</abbr>)
          </li>
          <li>
            <a href="/dcse/pdfs/CSFS_IWO.pdf">
              Income Withholding Order/Notice for Support (<span translate="no">IWO</span>)
            </a> (<abbr title="Portable Document Format" translate="no">PDF</abbr>)
          </li>
          <li>
            <a href="/dcse/pdfs/CSFS_LumpSum.pdf">Lump Sum Payments and Child Support</a>
            (<abbr title="Portable Document Format" translate="no">PDF</abbr>)
          </li>
          <li>
            <a href="pdfs/CSFS_NMSN.pdf">National Medical Support Notice</a>
            (<abbr title="Portable Document Format" translate="no">PDF</abbr>)
          </li>
          <li>
            <a href="/dcse/pdfs/empInfographic.pdf">
              Employers and Child Support: Infographic
            </a> (<abbr title="Portable Document Format" translate="no">PDF</abbr>)
          </li>
        </ul>
        {/* <!-- InstanceEndEditable --> */}
      </div>
      {/* <!-- End content div --> */}

      {/* <!-- End content div --> */}
      <div className="nys-global-footer">
        <div className="footer-container nys-global-footer-cols-2">
          <h3>Office of Temporary and Disability Assistance | Child Support</h3>
          <div className="footer-col">
            <h4>Child Support</h4>
            <ul>
              <li><a href="/DCSE/HomePage"><span>Child Support Home</span></a></li>
              <li><a href="/dcse/custodial_parent_services.html"><span>Custodial Parents</span></a></li>
              <li><a href="/dcse/non_custodial_parent_services.html"><span>Noncustodial Parents</span></a></li>
              <li><a href="/dcse/employers_new.html"><span className="capitalize">Employers</span></a></li>
              <li><a href="/dcse/providers.html"><span>Providers</span></a></li>
              <li><a href="/DCSE/LocalOffices_input"><span>Local Offices</span></a></li>
              <li><a href="/dcse/resources.html"><span>Resources</span></a></li>
            </ul>
          </div>
          <div className="footer-col">
            <h4>Office of Temporary and Disability Assistance</h4>
            <ul>
              <li><a href="https://otda.ny.gov/"><span className="notranslate" translate="no">OTDA</span> <span>Home</span></a></li>
              <li><a href="https://otda.ny.gov/contact.asp"><span>Contact</span> <span className="notranslate" translate="no">OTDA</span></a></li>
              {/* <!--li><a href="https://otda.ny.gov/legal/">Laws &amp; Policies</a></li--> */}
              <li><a href="https://otda.ny.gov/accessibility.asp"><span>Accessibility</span></a></li>
              <li><a href="https://otda.ny.gov/privacypolicy.asp"><span>Privacy Policy</span></a></li>
              <li><a href="https://otda.ny.gov/disclaimer.asp"><span>Disclaimer</span></a></li>
              <li><a href="https://otda.ny.gov/ada-notice.asp"><span>Notice under ADA</span></a></li>
              <li><a href="https://otda.ny.gov/legal/FOIL/"><span>Freedom of Information Law (FOIL)</span></a>
              </li>
            </ul>
          </div>

          <div className="social-media">
            <div className="social-media-title">
              <h4>CONNECT WITH US</h4>
            </div>
            <div className="social-media-links">
              <ul>
                <li>
                  <a href="https://facebook.com/nys.otda">
                    <span className="icon-social-facebook"></span>
                    <span>FACEBOOK</span>
                  </a>
                </li>
                <li>
                  <a href="https://flickr.com/photos/nysotda">
                    <span className="icon-social-flickr"></span>
                    <span>FLICKR</span>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/nysotda">
                    <span className="icon-social-twitter"></span>
                    <span>TWITTER</span>
                  </a>
                </li>
                <li>
                  <a href="https://youtube.com/user/NYStateOTDA">
                    <span className="icon-social-youtube"></span>
                    <span>YOUTUBE</span>
                  </a>
                </li>
                <li>
                  <a href="https://otda.ny.gov/news/feed/rss.xml">
                    <span className="icon-social-feed"></span>
                    <span>RSS FEED</span>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div id="program">
          <p>A Program of the <a href="https://otda.ny.gov"><span>Office of Temporary and Disability
            Assistance</span></a></p>
        </div>
      </div>
      {/* <!-- End nys-global-footer div --> */}
    
    </>
  )
}
